## predicting Livestock Growth Rates: A Custom Regression Analysis on Feed and Health Data

### Library Imports and Data Loading

In [1]:
import pandas as pd

In [7]:
file_path = 'data/uncleaned data/Livestock_Data.csv'
df = pd.read_csv( file_path)
df.head(10)

,CalfID,Pen,Block,Season_x,Phenotype,Growth,Milk,MBW,ADG,ODMI,...,MCP1,MIP1b,TNFa,VEGFa,BHV1,BHV1_Log,BVDV1,BVDV1_Log,BRSV,BRSV_Log
0,2505,4,2304,Fall,HH,H,H,91.644394,1.487013,14.125714,...,439.25,62.07,163.38,48.05,<4,0,32,5,.,.
1,2505,4,2304,Fall,HH,H,H,91.644394,1.487013,14.125714,...,495.88,60.32,87.45,46.01,<4,0,256,8,.,.
2,2505,4,2304,Fall,HH,H,H,91.644394,1.487013,14.125714,...,909.16,73.63,1251.11,58.45,<4,0,256,8,.,.
3,2505,4,2304,Fall,HH,H,H,91.644394,1.487013,14.125714,...,434.32,72.77,153.97,44.34,<4,0,64,6,.,.
4,2505,4,2304,Fall,HH,H,H,91.644394,1.487013,14.125714,...,395.44,169.95,265.95,58.71,<4,0,128,7,.,.
5,2510,3,2304,Fall,HH,H,H,94.577808,1.168831,14.169014,...,676.55,65.77,58.41,164.89,32,5,128,7,.,.
6,2510,3,2304,Fall,HH,H,H,94.577808,1.168831,14.169014,...,572.48,148.14,144.54,111.79,<4,0,256,8,.,.
7,2510,3,2304,Fall,HH,H,H,94.577808,1.168831,14.169014,...,476.06,222.76,344.45,118.52,8,3,128,7,.,.
8,2510,3,2304,Fall,HH,H,H,94.577808,1.168831,14.169014,...,501.98,102.33,395.04,89.92,<4,0,256,8,.,.
9,2510,3,2304,Fall,HH,H,H,94.577808,1.168831,14.169014,...,727.27,121.34,413.4,126.29,<4,0,256,8,.,.

In [8]:
file_path = 'data/uncleaned data/Data_Dictionary_Livestock.csv'
dic = pd.read_csv( file_path)
pd.set_option('display.max_colwidth', None)
dic.head(10)

,Column_Name,Description
0,CalfID,Unique identification number for each animal.
1,Pen,The specific enclosure or pen where the calf was housed.
2,Block,Experimental grouping or block used in the study design.
3,Season_x,The season during which performance data was recorded (Suffix from Merge).
4,Season_y,The season during which blood/immunity samples were taken (Suffix from Merge).
5,Year,The calendar year the data was collected.
6,Day,The specific day of the experiment or trial.
7,Timepoint,Specific temporal point when the sample or measurement was taken.
8,DamID,Unique identification number of the calf’s mother.
9,Sire,Unique identification number of the calf’s father (for genetic analysis).

## Task 1: data preprocessing